name: Daily Instagram Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # codziennie o 12:00 UTC

jobs:
  post_to_instagram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Instagram Post Script
      run: |
        export OPENAI_API_KEY = "${{ secrets.OPENAI_API_KEY }}"
        export INSTAGRAM_USERNAME = "${{ secrets.INSTAGRAM_USERNAME }}"
        export INSTAGRAM_PASSWORD = "${{ secrets.INSTAGRAM_PASSWORD }}"
        python main.py

    - name: Upload image as artifact (optional)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: instagram-image
        path: images/
