name: Instagram Comment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # codziennie o 12:00 UTC
    - cron: '0 18 * * *'  # codziennie o 18:00 UTC

jobs:
  comment_random_instagram_post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "INSTAGRAM_USERNAME=${{ secrets.INSTAGRAM_USERNAME }}" >> .env
        echo "INSTAGRAM_PASSWORD=${{ secrets.INSTAGRAM_PASSWORD }}" >> .env
        echo "CHALLENGE_EMAIL=${{ secrets.CHALLENGE_EMAIL }}" >> .env
        echo "CHALLENGE_PASSWORD=${{ secrets.CHALLENGE_PASSWORD }}" >> .env
        echo "${{ secrets.INSTAGRAM_SESSION }}" | base64 -d >> .env

    - name: Run Instagram Comment Script
      run: python instagram_add_comment.py
